/**
 * Tool metadata schema and tag taxonomy.
 */
export const TOOLSETS = [
  'core',
  'media',
  'voice',
  'wallet',
  'profile',
  'gallery',
  'secrets',
  'jobs',
  'reference',
  'models',
  'config',
  'admin',
  'diagnostics',
  'telegram',
  'twitter',
  'discord',
  'property',
  'memory',
  'nft',
  'claude-code',
  'github',
] as const;

export type ToolsetId = typeof TOOLSETS[number];

export const TOOL_TAGS = [
  'image',
  'video',
  'sticker',
  'voice',
  'audio',
  'tts',
  'transcribe',
  'wallet',
  'solana',
  'ethereum',
  'balance',
  'profile',
  'persona',
  'secrets',
  'token',
  'gallery',
  'reference',
  'jobs',
  'credits',
  'energy',
  'config',
  'model',
  'admin',
  'diagnostics',
  'telegram',
  'twitter',
  'discord',
  'property',
  'listings',
  'assessor',
  'schools',
  'memory',
  'recall',
  'remember',
  'nft',
  'ownership',
  'claude-code',
  'coding',
  'avatar',
  'presence',
  'channels',
  'cross-platform',
  'github',
  'issue-tracking',
  'deployed',
] as const;

export type ToolTag = typeof TOOL_TAGS[number];

export const CATEGORY_TOOLSET_MAP: Record<string, ToolsetId> = {
  media: 'media',
  wallet: 'wallet',
  profile: 'profile',
  config: 'config',
  gallery: 'gallery',
  secrets: 'secrets',
  readonly: 'core',
  diagnostics: 'diagnostics',
  telegram: 'telegram',
  property: 'property',
  nft: 'nft',
  github: 'github',
};

export const TOOLSET_DEFAULT_TAGS: Record<ToolsetId, ToolTag[]> = {
  core: [],
  media: ['image', 'video', 'sticker'],
  voice: ['voice', 'audio', 'tts', 'transcribe'],
  wallet: ['wallet', 'solana', 'ethereum', 'balance'],
  profile: ['profile', 'persona'],
  gallery: ['gallery', 'reference', 'image'],
  secrets: ['secrets', 'token'],
  jobs: ['jobs', 'credits', 'energy'],
  reference: ['reference', 'image'],
  models: ['model', 'config'],
  config: ['config'],
  admin: ['admin'],
  diagnostics: ['diagnostics'],
  telegram: ['telegram'],
  twitter: ['twitter'],
  discord: ['discord'],
  property: ['property', 'listings', 'assessor', 'schools'],
  memory: ['memory', 'recall', 'remember'],
  nft: ['nft', 'ownership'],
  'claude-code': ['claude-code', 'coding', 'avatar'],
  github: ['github', 'issue-tracking', 'deployed'],
};
